name = "fluxer_marketing"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.63.2 and < 1.0.0"
gleam_http = ">= 4.2.0 and < 5.0.0"
gleam_erlang = ">= 1.0.0 and < 2.0.0"
wisp = ">= 1.5.0 and < 2.0.0"
mist = ">= 5.0.0 and < 6.0.0"
lustre = ">= 5.0.0 and < 6.0.0"
kielet = ">= 3.0.0 and < 4.0.0"
nibble = ">= 1.1.4 and < 2.0.0"
simplifile = ">= 2.3.0 and < 3.0.0"
dot_env = ">= 1.2.0 and < 2.0.0"
gleam_regexp = ">= 1.1.1 and < 2.0.0"
gleam_httpc = ">= 5.0.0 and < 6.0.0"
gleam_json = ">= 3.0.2 and < 4.0.0"
envoy = ">= 1.0.2 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.6.1 and < 2.0.0"
glailglind = ">= 2.2.0 and < 3.0.0"
